// <auto-generated />
using System;
using CoffeeInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeInventory.Infrastructure.Migrations
{
    [DbContext(typeof(CoffeeInventoryDbContext))]
    [Migration("20260716151725_RemoveSerialColumn")]
    partial class RemoveSerialColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SerialSequence")
                .StartsAt(1000L);

            modelBuilder.Entity("CoffeeCupSize", b =>
                {
                    b.Property<Guid>("CoffeesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CupSizesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoffeesId", "CupSizesId");

                    b.HasIndex("CupSizesId");

                    b.ToTable("CoffeeCupSize", (string)null);
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.CapsuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CapsuleTypes");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CapsuleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Consumed")
                        .HasColumnType("int");

                    b.Property<bool>("IsDecaffeinated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapsuleTypeId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.CupSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CupSizes");
                });

            modelBuilder.Entity("CoffeeCupSize", b =>
                {
                    b.HasOne("CoffeeInventory.Domain.Entities.Coffee", null)
                        .WithMany()
                        .HasForeignKey("CoffeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeInventory.Domain.Entities.CupSize", null)
                        .WithMany()
                        .HasForeignKey("CupSizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Coffee", b =>
                {
                    b.HasOne("CoffeeInventory.Domain.Entities.CapsuleType", "CapsuleType")
                        .WithMany()
                        .HasForeignKey("CapsuleTypeId");

                    b.Navigation("CapsuleType");
                });
#pragma warning restore 612, 618
        }
    }
}
