// <auto-generated />
using System;
using CoffeeInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeInventory.Infrastructure.Migrations
{
    [DbContext(typeof(CoffeeInventoryDbContext))]
    [Migration("20260722172755_UpdateDatabaseConfigurations")]
    partial class UpdateDatabaseConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeCupSizes", b =>
                {
                    b.Property<Guid>("CoffeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CupSizeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoffeeId", "CupSizeId");

                    b.HasIndex("CupSizeId");

                    b.ToTable("CoffeeCupSizes");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.CapsuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CapsuleTypes");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Coffee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CapsuleTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Consumed")
                        .HasColumnType("int");

                    b.Property<bool>("IsDecaffeinated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CapsuleTypeId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.CupSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CupSizes");
                });

            modelBuilder.Entity("CoffeeCupSizes", b =>
                {
                    b.HasOne("CoffeeInventory.Domain.Entities.Coffee", null)
                        .WithMany()
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeInventory.Domain.Entities.CupSize", null)
                        .WithMany()
                        .HasForeignKey("CupSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Coffee", b =>
                {
                    b.HasOne("CoffeeInventory.Domain.Entities.Brand", "Brand")
                        .WithMany("Coffees")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoffeeInventory.Domain.Entities.CapsuleType", "CapsuleType")
                        .WithMany("Coffees")
                        .HasForeignKey("CapsuleTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("CapsuleType");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Coffees");
                });

            modelBuilder.Entity("CoffeeInventory.Domain.Entities.CapsuleType", b =>
                {
                    b.Navigation("Coffees");
                });
#pragma warning restore 612, 618
        }
    }
}
